### ISSUE TITLE
Tag.Custom doesn't render content

### ISSUE THREAD

**Issue by SCullman** [2sic/razor-blade#21]
`@Tag.Custom("h1","Have fun in Millau")` renders to `<h1></h1>`

## Expected
It should render to `<h1>Have fun in Millau</h1>`

## Environment
Tested with DNN 9.10.2., 2sxc V14.0.7 and current templates for content.

**Comment by iJungleboy** [comment]
thx, will check asap!

**Comment by iJungleboy** [comment]
I can verify the bug, fixing it. Thx for the speedy issue report !
